/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading COIN Futures REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading COIN Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInformationResponseRateLimitsInner } from './exchange-information-response-rate-limits-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExchangeInformationResponseSymbolsInner } from './exchange-information-response-symbols-inner';

/**
 *
 * @export
 * @interface ExchangeInformationResponse
 */
export interface ExchangeInformationResponse {
    /**
     *
     * @type {Array<string>}
     * @memberof ExchangeInformationResponse
     */
    exchangeFilters?: Array<string>;
    /**
     *
     * @type {Array<ExchangeInformationResponseRateLimitsInner>}
     * @memberof ExchangeInformationResponse
     */
    rateLimits?: Array<ExchangeInformationResponseRateLimitsInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof ExchangeInformationResponse
     */
    serverTime?: number | bigint;
    /**
     *
     * @type {Array<ExchangeInformationResponseSymbolsInner>}
     * @memberof ExchangeInformationResponse
     */
    symbols?: Array<ExchangeInformationResponseSymbolsInner>;
    /**
     *
     * @type {string}
     * @memberof ExchangeInformationResponse
     */
    timezone?: string;
}
