/* tslint:disable */
/* eslint-disable */

/**
 * Binance Spot WebSocket API
 *
 * OpenAPI Specifications for the Binance Spot WebSocket API
 *
 * API documents:
 * - [Github web-socket-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-api.md)
 * - [General API information for web-socket-api on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountCommissionResponseResult } from './account-commission-response-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RateLimits } from './rate-limits';

/**
 *
 * @export
 * @interface AccountCommissionResponse
 */
export interface AccountCommissionResponse {
    /**
     *
     * @type {string}
     * @memberof AccountCommissionResponse
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountCommissionResponse
     */
    status?: number | bigint;
    /**
     *
     * @type {AccountCommissionResponseResult}
     * @memberof AccountCommissionResponse
     */
    result?: AccountCommissionResponseResult;
    /**
     *
     * @type {Array<RateLimits>}
     * @memberof AccountCommissionResponse
     */
    rateLimits?: Array<RateLimits>;
}
