/* tslint:disable */

/**
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryMarginAccountsOpenOcoResponseInnerOrdersInner
 */
export interface QueryMarginAccountsOpenOcoResponseInnerOrdersInner {
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInnerOrdersInner
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsOpenOcoResponseInnerOrdersInner
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInnerOrdersInner
     */
    clientOrderId?: string;
}
