/* tslint:disable */

/**
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QuerySpecialKeyResponse
 */
export interface QuerySpecialKeyResponse {
    /**
     *
     * @type {string}
     * @memberof QuerySpecialKeyResponse
     */
    apiKey?: string;
    /**
     *
     * @type {string}
     * @memberof QuerySpecialKeyResponse
     */
    ip?: string;
    /**
     *
     * @type {string}
     * @memberof QuerySpecialKeyResponse
     */
    apiName?: string;
    /**
     *
     * @type {string}
     * @memberof QuerySpecialKeyResponse
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof QuerySpecialKeyResponse
     */
    permissionMode?: string;
}
