/* tslint:disable */

/**
 * Binance Margin Trading REST API
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryMarginAccountsTradeListResponseInner
 */
export interface QueryMarginAccountsTradeListResponseInner {
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    commission?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    commissionAsset?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    id?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    isBestMatch?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    isBuyer?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    isMaker?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    qty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    isIsolated?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsTradeListResponseInner
     */
    time?: number | bigint;
}
