/**
 * Binance Rebate REST API
 *
 * OpenAPI Specification for the Binance Rebate REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfigurationRestAPI, RestApiResponse, sendRequest } from '@binance/common';
import { RebateApi } from './modules/rebate-api';

import type { GetSpotRebateHistoryRecordsRequest } from './modules/rebate-api';

import type { GetSpotRebateHistoryRecordsResponse } from './types';

export class RestAPI {
    private configuration: ConfigurationRestAPI;
    private rebateApi: RebateApi;

    constructor(configuration: ConfigurationRestAPI) {
        this.configuration = configuration;
        this.rebateApi = new RebateApi(configuration);
    }

    /**
     * Generic function to send a request.
     * @param endpoint - The API endpoint to call.
     * @param method - HTTP method to use (GET, POST, DELETE, etc.).
     * @param queryParams - Query parameters for the request.
     * @param bodyParams - Body parameters for the request.
     *
     * @returns A promise resolving to the response data object.
     */
    sendRequest<T>(
        endpoint: string,
        method: 'GET' | 'POST' | 'DELETE' | 'PUT' | 'PATCH',
        queryParams: Record<string, unknown> = {},
        bodyParams: Record<string, unknown> = {}
    ): Promise<RestApiResponse<T>> {
        return sendRequest<T>(
            this.configuration,
            endpoint,
            method,
            queryParams,
            bodyParams,
            undefined
        );
    }

    /**
     * Generic function to send a signed request.
     * @param endpoint - The API endpoint to call.
     * @param method - HTTP method to use (GET, POST, DELETE, etc.).
     * @param queryParams - Query parameters for the request.
     * @param bodyParams - Body parameters for the request.
     *
     * @returns A promise resolving to the response data object.
     */
    sendSignedRequest<T>(
        endpoint: string,
        method: 'GET' | 'POST' | 'DELETE' | 'PUT' | 'PATCH',
        queryParams: Record<string, unknown> = {},
        bodyParams: Record<string, unknown> = {}
    ): Promise<RestApiResponse<T>> {
        return sendRequest<T>(
            this.configuration,
            endpoint,
            method,
            queryParams,
            bodyParams,
            undefined,
            { isSigned: true }
        );
    }

    /**
     * Get Spot Rebate History Records
     *
     * The max interval between startTime and endTime is 30 days.
     * If startTime and endTime are not sent, the recent 7 days' data will be returned.
     * The earliest startTime is supported on June 10, 2020
     * Return up to 200 records per request.
     *
     * Weight: 12000
     *
     * @summary Get Spot Rebate History Records (USER_DATA)
     * @param {GetSpotRebateHistoryRecordsRequest} requestParameters Request parameters.
     *
     * @returns {Promise<RestApiResponse<GetSpotRebateHistoryRecordsResponse>>}
     * @throws {RequiredError | ConnectorClientError | UnauthorizedError | ForbiddenError | TooManyRequestsError | RateLimitBanError | ServerError | NotFoundError | NetworkError | BadRequestError}
     * @see {@link https://developers.binance.com/docs/rebate/rest-api/Get-Spot-Rebate-History-Records Binance API Documentation}
     */
    getSpotRebateHistoryRecords(
        requestParameters: GetSpotRebateHistoryRecordsRequest = {}
    ): Promise<RestApiResponse<GetSpotRebateHistoryRecordsResponse>> {
        return this.rebateApi.getSpotRebateHistoryRecords(requestParameters);
    }
}
