/* tslint:disable */

/**
 * Binance Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AggregateTradeStreamsResponse
 */
export interface AggregateTradeStreamsResponse {
    /**
     *
     * @type {string}
     * @memberof AggregateTradeStreamsResponse
     */
    e?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AggregateTradeStreamsResponse
     */
    E?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AggregateTradeStreamsResponse
     */
    a?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AggregateTradeStreamsResponse
     */
    s?: string;
    /**
     *
     * @type {string}
     * @memberof AggregateTradeStreamsResponse
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof AggregateTradeStreamsResponse
     */
    q?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AggregateTradeStreamsResponse
     */
    f?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AggregateTradeStreamsResponse
     */
    l?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AggregateTradeStreamsResponse
     */
    T?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof AggregateTradeStreamsResponse
     */
    m?: boolean;
}
