/* tslint:disable */

/**
 * Binance Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading COIN Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Listenkeyexpired
 */
export interface Listenkeyexpired {
    /**
     *
     * @type {number | bigint}
     * @memberof Listenkeyexpired
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof Listenkeyexpired
     */
    listenKey?: string;
}
