/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading USDS Futures REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CompositeIndexSymbolInformationResponseInnerBaseAssetListInner } from './composite-index-symbol-information-response-inner-base-asset-list-inner';

/**
 *
 * @export
 * @interface CompositeIndexSymbolInformationResponseInner
 */
export interface CompositeIndexSymbolInformationResponseInner {
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof CompositeIndexSymbolInformationResponseInner
     */
    time?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationResponseInner
     */
    component?: string;
    /**
     *
     * @type {Array<CompositeIndexSymbolInformationResponseInnerBaseAssetListInner>}
     * @memberof CompositeIndexSymbolInformationResponseInner
     */
    baseAssetList?: Array<CompositeIndexSymbolInformationResponseInnerBaseAssetListInner>;
}
