/* tslint:disable */
/* eslint-disable */

/**
 * Binance Wallet REST API
 *
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AssetDividendRecordResponseRowsInner } from './asset-dividend-record-response-rows-inner';

/**
 *
 * @export
 * @interface AssetDividendRecordResponse
 */
export interface AssetDividendRecordResponse {
    /**
     *
     * @type {Array<AssetDividendRecordResponseRowsInner>}
     * @memberof AssetDividendRecordResponse
     */
    rows?: Array<AssetDividendRecordResponseRowsInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof AssetDividendRecordResponse
     */
    total?: number | bigint;
}
