/* tslint:disable */

/**
 * Binance Wallet REST API
 *
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DepositHistoryResponseInner
 */
export interface DepositHistoryResponseInner {
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    coin?: string;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    network?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    status?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    address?: string;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    addressTag?: string;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    txId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    insertTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    completeTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    transferType?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof DepositHistoryResponseInner
     */
    confirmTimes?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    unlockConfirm?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    walletType?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof DepositHistoryResponseInner
     */
    travelRuleStatus?: number | bigint;
}
