/* tslint:disable */

/**
 * Binance Wallet REST API
 *
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DustConvertibleAssetsResponseDetailsInner
 */
export interface DustConvertibleAssetsResponseDetailsInner {
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    assetFullName?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    amountFree?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    exchange?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    toQuotaAssetAmount?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    toTargetAssetAmount?: string;
    /**
     *
     * @type {string}
     * @memberof DustConvertibleAssetsResponseDetailsInner
     */
    toTargetAssetOffExchange?: string;
}
