/* tslint:disable */

/**
 * Binance Wallet REST API
 *
 * OpenAPI Specification for the Binance Wallet REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetApiKeyPermissionResponse
 */
export interface GetApiKeyPermissionResponse {
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    ipRestrict?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof GetApiKeyPermissionResponse
     */
    createTime?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableReading?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableWithdrawals?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableInternalTransfer?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableMargin?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableFutures?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    permitsUniversalTransfer?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableVanillaOptions?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableFixApiTrade?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableFixReadOnly?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enableSpotAndMarginTrading?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetApiKeyPermissionResponse
     */
    enablePortfolioMarginTrading?: boolean;
}
