/* tslint:disable */
/* eslint-disable */

/**
 * Binance Mining REST API
 *
 * OpenAPI Specification for the Binance Mining REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExtraBonusListResponseDataOtherProfitsInner } from './extra-bonus-list-response-data-other-profits-inner';

/**
 *
 * @export
 * @interface ExtraBonusListResponseData
 */
export interface ExtraBonusListResponseData {
    /**
     *
     * @type {Array<ExtraBonusListResponseDataOtherProfitsInner>}
     * @memberof ExtraBonusListResponseData
     */
    otherProfits?: Array<ExtraBonusListResponseDataOtherProfitsInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof ExtraBonusListResponseData
     */
    totalNum?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof ExtraBonusListResponseData
     */
    pageSize?: number | bigint;
}
