/* tslint:disable */

/**
 * Binance Dual Investment REST API
 *
 * OpenAPI Specification for the Binance Dual Investment REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CheckDualInvestmentAccountsResponse
 */
export interface CheckDualInvestmentAccountsResponse {
    /**
     *
     * @type {string}
     * @memberof CheckDualInvestmentAccountsResponse
     */
    totalAmountInBTC?: string;
    /**
     *
     * @type {string}
     * @memberof CheckDualInvestmentAccountsResponse
     */
    totalAmountInUSDT?: string;
}
