/* tslint:disable */

/**
 * Binance VIP Loan REST API
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetLoanableAssetsDataResponseRowsInner
 */
export interface GetLoanableAssetsDataResponseRowsInner {
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    loanCoin?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _flexibleDailyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _flexibleYearlyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _30dDailyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _30dYearlyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _60dDailyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    _60dYearlyInterestRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    minLimit?: string;
    /**
     *
     * @type {string}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    maxLimit?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetLoanableAssetsDataResponseRowsInner
     */
    vipLevel?: number | bigint;
}
