/* tslint:disable */

/**
 * Binance Spot WebSocket Streams
 *
 * OpenAPI Specifications for the Binance Spot WebSocket Streams
 *
 * API documents:
 * - [Github web-socket-streams documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md)
 * - [General API information for web-socket-streams on website](https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradeResponse
 */
export interface TradeResponse {
    /**
     *
     * @type {string}
     * @memberof TradeResponse
     */
    e?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TradeResponse
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof TradeResponse
     */
    s?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TradeResponse
     */
    t?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof TradeResponse
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof TradeResponse
     */
    q?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof TradeResponse
     */
    T?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof TradeResponse
     */
    m?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof TradeResponse
     */
    M?: boolean;
}
