/* tslint:disable */

/**
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountBlockTradeListResponseInnerLegsInner
 */
export interface AccountBlockTradeListResponseInnerLegsInner {
    /**
     *
     * @type {number | bigint}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    createTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderId?: string;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderPrice?: number;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderQuantity?: number;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderStatus?: string;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    executedQty?: number;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    executedAmount?: number;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    fee?: number;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderType?: string;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    orderSide?: string;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    id?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    tradeId?: number | bigint;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    tradePrice?: number;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    tradeQty?: number;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    tradeTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    liquidity?: string;
    /**
     *
     * @type {number}
     * @memberof AccountBlockTradeListResponseInnerLegsInner
     */
    commission?: number;
}
