/* tslint:disable */

/**
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IndexPriceResponse
 */
export interface IndexPriceResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof IndexPriceResponse
     */
    time?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof IndexPriceResponse
     */
    indexPrice?: string;
}
