/* tslint:disable */

/**
 * Binance Derivatives Trading Options REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Options REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PlaceMultipleOrdersOrdersParameterInner
 */
export interface PlaceMultipleOrdersOrdersParameterInner {
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    side?: PlaceMultipleOrdersOrdersParameterInnerSideEnum;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    type?: PlaceMultipleOrdersOrdersParameterInnerTypeEnum;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    quantity?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    timeInForce?: PlaceMultipleOrdersOrdersParameterInnerTimeInForceEnum;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    reduceOnly?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    postOnly?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    newOrderRespType?: PlaceMultipleOrdersOrdersParameterInnerNewOrderRespTypeEnum;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    clientOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof PlaceMultipleOrdersOrdersParameterInner
     */
    isMmp?: string;
}

export const PlaceMultipleOrdersOrdersParameterInnerSideEnum = {
    BUY: 'BUY',
    SELL: 'SELL',
} as const;

export type PlaceMultipleOrdersOrdersParameterInnerSideEnum =
    (typeof PlaceMultipleOrdersOrdersParameterInnerSideEnum)[keyof typeof PlaceMultipleOrdersOrdersParameterInnerSideEnum];
export const PlaceMultipleOrdersOrdersParameterInnerTypeEnum = {
    LIMIT: 'LIMIT',
} as const;

export type PlaceMultipleOrdersOrdersParameterInnerTypeEnum =
    (typeof PlaceMultipleOrdersOrdersParameterInnerTypeEnum)[keyof typeof PlaceMultipleOrdersOrdersParameterInnerTypeEnum];
export const PlaceMultipleOrdersOrdersParameterInnerTimeInForceEnum = {
    GTC: 'GTC',
    IOC: 'IOC',
    FOK: 'FOK',
    GTX: 'GTX',
} as const;

export type PlaceMultipleOrdersOrdersParameterInnerTimeInForceEnum =
    (typeof PlaceMultipleOrdersOrdersParameterInnerTimeInForceEnum)[keyof typeof PlaceMultipleOrdersOrdersParameterInnerTimeInForceEnum];
export const PlaceMultipleOrdersOrdersParameterInnerNewOrderRespTypeEnum = {
    ACK: 'ACK',
    RESULT: 'RESULT',
} as const;

export type PlaceMultipleOrdersOrdersParameterInnerNewOrderRespTypeEnum =
    (typeof PlaceMultipleOrdersOrdersParameterInnerNewOrderRespTypeEnum)[keyof typeof PlaceMultipleOrdersOrdersParameterInnerNewOrderRespTypeEnum];
