/* tslint:disable */
/* eslint-disable */

/**
 * Binance Algo REST API
 *
 * OpenAPI Specification for the Binance Algo REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryCurrentAlgoOpenOrdersFutureAlgoResponseOrdersInner } from './query-current-algo-open-orders-future-algo-response-orders-inner';

/**
 *
 * @export
 * @interface QueryCurrentAlgoOpenOrdersFutureAlgoResponse
 */
export interface QueryCurrentAlgoOpenOrdersFutureAlgoResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCurrentAlgoOpenOrdersFutureAlgoResponse
     */
    total?: number | bigint;
    /**
     *
     * @type {Array<QueryCurrentAlgoOpenOrdersFutureAlgoResponseOrdersInner>}
     * @memberof QueryCurrentAlgoOpenOrdersFutureAlgoResponse
     */
    orders?: Array<QueryCurrentAlgoOpenOrdersFutureAlgoResponseOrdersInner>;
}
