/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CancelAllCmOpenOrdersResponse
 */
export interface CancelAllCmOpenOrdersResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof CancelAllCmOpenOrdersResponse
     */
    code?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof CancelAllCmOpenOrdersResponse
     */
    msg?: string;
}
