/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetUmFuturesTransactionDownloadLinkByIdResponse
 */
export interface GetUmFuturesTransactionDownloadLinkByIdResponse {
    /**
     *
     * @type {string}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    downloadId?: string;
    /**
     *
     * @type {string}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    url?: string;
    /**
     *
     * @type {string}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    s3Link?: string;
    /**
     *
     * @type {boolean}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    notified?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    expirationTimestamp?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof GetUmFuturesTransactionDownloadLinkByIdResponse
     */
    isExpired?: string;
}
