/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ModifyUmOrderResponse
 */
export interface ModifyUmOrderResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof ModifyUmOrderResponse
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    clientOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    avgPrice?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    cumQty?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    cumQuote?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    type?: string;
    /**
     *
     * @type {boolean}
     * @memberof ModifyUmOrderResponse
     */
    reduceOnly?: boolean;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    positionSide?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    origType?: string;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof ModifyUmOrderResponse
     */
    goodTillDate?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof ModifyUmOrderResponse
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof ModifyUmOrderResponse
     */
    priceMatch?: string;
}
