/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryCmPositionInformationResponseInner
 */
export interface QueryCmPositionInformationResponseInner {
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    positionAmt?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    entryPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    markPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    unRealizedProfit?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    liquidationPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    leverage?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    positionSide?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCmPositionInformationResponseInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    maxQty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCmPositionInformationResponseInner
     */
    notionalValue?: string;
}
