/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryCurrentMarginOpenOrderResponseInner
 */
export interface QueryCurrentMarginOpenOrderResponseInner {
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    clientOrderId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    cummulativeQuoteQty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    icebergQty?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    isWorking?: boolean;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    stopPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    time?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    type?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    accountId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    preventedMatchId?: string;
    /**
     *
     * @type {string}
     * @memberof QueryCurrentMarginOpenOrderResponseInner
     */
    preventedQuantity?: string;
}
