/* tslint:disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface QueryAllUmConditionalOrdersResponseInner
 */
export interface QueryAllUmConditionalOrdersResponseInner {
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    newClientStrategyId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    strategyId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    strategyStatus?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    strategyType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    price?: string;
    /**
     *
     * @type {boolean}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    reduceOnly?: boolean;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    side?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    positionSide?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    stopPrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    orderId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    status?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    bookTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    updateTime?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    triggerTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    activatePrice?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    priceRate?: string;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    goodTillDate?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryAllUmConditionalOrdersResponseInner
     */
    priceMatch?: string;
}
