/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading Portfolio Margin REST API
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QueryMarginAccountsOpenOcoResponseInnerOrdersInner } from './query-margin-accounts-open-oco-response-inner-orders-inner';

/**
 *
 * @export
 * @interface QueryMarginAccountsOpenOcoResponseInner
 */
export interface QueryMarginAccountsOpenOcoResponseInner {
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    contingencyType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listStatusType?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listOrderStatus?: string;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    listClientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    transactionTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    symbol?: string;
    /**
     *
     * @type {Array<QueryMarginAccountsOpenOcoResponseInnerOrdersInner>}
     * @memberof QueryMarginAccountsOpenOcoResponseInner
     */
    orders?: Array<QueryMarginAccountsOpenOcoResponseInnerOrdersInner>;
}
