/* tslint:disable */

/**
 * Binance Margin Trading WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Margin Trading WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserLiabilityChange
 */
export interface UserLiabilityChange {
    /**
     *
     * @type {number | bigint}
     * @memberof UserLiabilityChange
     */
    E?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof UserLiabilityChange
     */
    a?: string;
    /**
     *
     * @type {string}
     * @memberof UserLiabilityChange
     */
    t?: string;
    /**
     *
     * @type {string}
     * @memberof UserLiabilityChange
     */
    p?: string;
    /**
     *
     * @type {string}
     * @memberof UserLiabilityChange
     */
    i?: string;
}
