/* tslint:disable */
/* eslint-disable */

/**
 * Binance Simple Earn REST API
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetRwusdRedemptionHistoryResponseRowsInner } from './get-rwusd-redemption-history-response-rows-inner';

/**
 *
 * @export
 * @interface GetRwusdRedemptionHistoryResponse
 */
export interface GetRwusdRedemptionHistoryResponse {
    /**
     *
     * @type {Array<GetRwusdRedemptionHistoryResponseRowsInner>}
     * @memberof GetRwusdRedemptionHistoryResponse
     */
    rows?: Array<GetRwusdRedemptionHistoryResponseRowsInner>;
    /**
     *
     * @type {number | bigint}
     * @memberof GetRwusdRedemptionHistoryResponse
     */
    total?: number | bigint;
}
