/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetCurrentEthStakingQuotaResponse
 */
export interface GetCurrentEthStakingQuotaResponse {
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    leftStakingPersonalQuota?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    leftRedemptionPersonalQuota?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    minStakeAmount?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    minRedeemAmount?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    redeemPeriod?: number | bigint;
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    stakeable?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    redeemable?: boolean;
    /**
     *
     * @type {string}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    commissionFee?: string;
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentEthStakingQuotaResponse
     */
    calculating?: boolean;
}
