/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
 */
export interface GetOnChainYieldsLockedRedemptionRecordResponseRowsInner {
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    positionId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    redeemId?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    time?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    asset?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    lockPeriod?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    amount?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    originalAmount?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    deliverDate?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    lossAmount?: string;
    /**
     *
     * @type {boolean}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    isComplete?: boolean;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    rewardAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    rewardAmt?: string;
    /**
     *
     * @type {string}
     * @memberof GetOnChainYieldsLockedRedemptionRecordResponseRowsInner
     */
    status?: string;
}
