/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetWbethWrapHistoryResponseRowsInner
 */
export interface GetWbethWrapHistoryResponseRowsInner {
    /**
     *
     * @type {number | bigint}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    time?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    fromAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    fromAmount?: string;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    toAsset?: string;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    toAmount?: string;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    exchangeRate?: string;
    /**
     *
     * @type {string}
     * @memberof GetWbethWrapHistoryResponseRowsInner
     */
    status?: string;
}
