/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OnChainYieldsAccountResponse
 */
export interface OnChainYieldsAccountResponse {
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalAmountInBTC?: string;
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalAmountInUSDT?: string;
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalFlexibleAmountInBTC?: string;
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalFlexibleAmountInUSDT?: string;
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalLockedInBTC?: string;
    /**
     *
     * @type {string}
     * @memberof OnChainYieldsAccountResponse
     */
    totalLockedInUSDT?: string;
}
