/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RedeemEthResponse
 */
export interface RedeemEthResponse {
    /**
     *
     * @type {boolean}
     * @memberof RedeemEthResponse
     */
    success?: boolean;
    /**
     *
     * @type {string}
     * @memberof RedeemEthResponse
     */
    ethAmount?: string;
    /**
     *
     * @type {string}
     * @memberof RedeemEthResponse
     */
    conversionRatio?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof RedeemEthResponse
     */
    arrivalTime?: number | bigint;
}
