/* tslint:disable */

/**
 * Binance Staking REST API
 *
 * OpenAPI Specification for the Binance Staking REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SubscribeEthStakingResponse
 */
export interface SubscribeEthStakingResponse {
    /**
     *
     * @type {boolean}
     * @memberof SubscribeEthStakingResponse
     */
    success?: boolean;
    /**
     *
     * @type {string}
     * @memberof SubscribeEthStakingResponse
     */
    wbethAmount?: string;
    /**
     *
     * @type {string}
     * @memberof SubscribeEthStakingResponse
     */
    conversionRatio?: string;
}
