/* tslint:disable */
/* eslint-disable */

/**
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QuerySubAccountSpotAssetsSummaryResponseSpotSubUserAssetBtcVoListInner } from './query-sub-account-spot-assets-summary-response-spot-sub-user-asset-btc-vo-list-inner';

/**
 *
 * @export
 * @interface QuerySubAccountSpotAssetsSummaryResponse
 */
export interface QuerySubAccountSpotAssetsSummaryResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof QuerySubAccountSpotAssetsSummaryResponse
     */
    totalCount?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof QuerySubAccountSpotAssetsSummaryResponse
     */
    masterAccountTotalAsset?: string;
    /**
     *
     * @type {Array<QuerySubAccountSpotAssetsSummaryResponseSpotSubUserAssetBtcVoListInner>}
     * @memberof QuerySubAccountSpotAssetsSummaryResponse
     */
    spotSubUserAssetBtcVoList?: Array<QuerySubAccountSpotAssetsSummaryResponseSpotSubUserAssetBtcVoListInner>;
}
