/* tslint:disable */
/* eslint-disable */

/**
 * Binance Sub Account REST API
 *
 * OpenAPI Specification for the Binance Sub Account REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { QuerySubAccountAssetsAssetManagementResponseBalancesInner } from './query-sub-account-assets-asset-management-response-balances-inner';

/**
 *
 * @export
 * @interface QuerySubAccountAssetsAssetManagementResponse
 */
export interface QuerySubAccountAssetsAssetManagementResponse {
    /**
     *
     * @type {Array<QuerySubAccountAssetsAssetManagementResponseBalancesInner>}
     * @memberof QuerySubAccountAssetsAssetManagementResponse
     */
    balances?: Array<QuerySubAccountAssetsAssetManagementResponseBalancesInner>;
}
