/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountConfigUpdateAc } from './account-config-update-ac';

/**
 *
 * @export
 * @interface AccountConfigUpdate
 */
export interface AccountConfigUpdate {
    /**
     *
     * @type {string}
     * @memberof AccountConfigUpdate
     */
    fs?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountConfigUpdate
     */
    E?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountConfigUpdate
     */
    T?: number | bigint;
    /**
     *
     * @type {AccountConfigUpdateAc}
     * @memberof AccountConfigUpdate
     */
    ac?: AccountConfigUpdateAc;
}
