/* tslint:disable */
/* eslint-disable */

/**
 * Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AccountUpdateA } from './account-update-a';

/**
 *
 * @export
 * @interface AccountUpdate
 */
export interface AccountUpdate {
    /**
     *
     * @type {number | bigint}
     * @memberof AccountUpdate
     */
    E?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof AccountUpdate
     */
    T?: number | bigint;
    /**
     *
     * @type {AccountUpdateA}
     * @memberof AccountUpdate
     */
    a?: AccountUpdateA;
}
