/* tslint:disable */

/**
 * Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures WebSocket Market Streams
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CompositeIndexSymbolInformationStreamsResponseCInner
 */
export interface CompositeIndexSymbolInformationStreamsResponseCInner {
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponseCInner
     */
    b?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponseCInner
     */
    q?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponseCInner
     */
    w?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponseCInner
     */
    W?: string;
    /**
     *
     * @type {string}
     * @memberof CompositeIndexSymbolInformationStreamsResponseCInner
     */
    i?: string;
}
