/* tslint:disable */
/* eslint-disable */

/**
 * Binance NFT REST API
 *
 * OpenAPI Specification for the Binance NFT REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetNFTTransactionHistoryResponseListInner } from './get-nfttransaction-history-response-list-inner';

/**
 *
 * @export
 * @interface GetNFTTransactionHistoryResponse
 */
export interface GetNFTTransactionHistoryResponse {
    /**
     *
     * @type {number | bigint}
     * @memberof GetNFTTransactionHistoryResponse
     */
    total?: number | bigint;
    /**
     *
     * @type {Array<GetNFTTransactionHistoryResponseListInner>}
     * @memberof GetNFTTransactionHistoryResponse
     */
    list?: Array<GetNFTTransactionHistoryResponseListInner>;
}
