/* tslint:disable */
/* eslint-disable */

/**
 * Binance Spot REST API
 *
 * OpenAPI Specifications for the Binance Spot REST API
 *
 * API documents:
 * - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)
 * - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SorOrderResponseFillsInner } from './sor-order-response-fills-inner';

/**
 *
 * @export
 * @interface SorOrderResponse
 */
export interface SorOrderResponse {
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    symbol?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof SorOrderResponse
     */
    orderId?: number | bigint;
    /**
     *
     * @type {number | bigint}
     * @memberof SorOrderResponse
     */
    orderListId?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    clientOrderId?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof SorOrderResponse
     */
    transactTime?: number | bigint;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    price?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    origQty?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    executedQty?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    origQuoteOrderQty?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    cummulativeQuoteQty?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    status?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    timeInForce?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    side?: string;
    /**
     *
     * @type {number | bigint}
     * @memberof SorOrderResponse
     */
    workingTime?: number | bigint;
    /**
     *
     * @type {Array<SorOrderResponseFillsInner>}
     * @memberof SorOrderResponse
     */
    fills?: Array<SorOrderResponseFillsInner>;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    workingFloor?: string;
    /**
     *
     * @type {string}
     * @memberof SorOrderResponse
     */
    selfTradePreventionMode?: string;
    /**
     *
     * @type {boolean}
     * @memberof SorOrderResponse
     */
    usedSor?: boolean;
}
